name: Build

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo install --verbose --path .
    - name: Tests
      run: cargo test --verbose
